diffusion:
  target: ldm.models.diffusion.ldm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    timesteps: 1000
   

model:
  target: ldm.modules.diffusionmodules.openaimodel.UNetModel
  params:
    image_size: 64
    in_channels: 4
    out_channels: 4
    model_channels: 320
    attention_resolutions: [ 4, 2, 1 ]
    num_res_blocks: 2
    channel_mult: [ 1, 2, 4, 4 ]
    num_heads: 8
    transformer_depth: 1
    context_dim: 768
    fuser_type: gatedSA
    use_checkpoint: True

    grounding_tokenizer:
      target: ldm.modules.diffusionmodules.text_grounding_net.PositionNet
      params:
        in_dim: 768
        out_dim: 768


autoencoder:
  target: ldm.models.autoencoder_lp.DUALAutoencoderLP
  params:
    scale_factor: 0.18215 
    embed_dim: 4
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 256
      # in_channels: 6
      in_channels: 128
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0


text_encoder:
  target: ldm.modules.encoders.modules.FrozenLongCLIPEmbedder




train_dataset_names: 
  FlirGrounding:
    image_size: 512
    max_boxes_per_data: 30
    prob_use_caption: 0.5
    random_crop: True
    random_flip: True 
    min_box_size: 0.0001


grounding_tokenizer_input:
  target: grounding_input.text_grounding_tokinzer_input.GroundingNetInput

